### ISSUE TITLE
publishApk task fails with NoSuchMethodError: AbstractGoogleJsonClient$Builder.setBatchPath after updating to 1.2.2

### ISSUE THREAD

**Issue by Nimrodda** [Triple-T/gradle-play-publisher#344]
`publishApkBrandStoreRelease` task fails with 
```
java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder
.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
```
After we updated the plugin to 1.2.2 from 1.2.0.
We reverted back to 1.2.0 for now.

Our project has multiple dimensions in the following order: brand, store, buildType.
Example variant: FooPlaystoreRelease.

**Comment by SUPERCILEX** [comment]
Would you mind sharing the output of `./gradlew buildEnvironment`?

**Comment by Nimrodda** [comment]
Here you go https://pastebin.com/dwY3EgNy

**Comment by SUPERCILEX** [comment]
Thanks! This isn't an issue in the upcoming v2.0 release. In the meantime, you can add this workaround: https://github.com/GoogleCloudPlatform/getting-started-java/issues/325#issuecomment-377171975.

**Comment by Nimrodda** [comment]
Alright, thank you! :)

**Comment by mehdiraza** [comment]
I am getting this error on v2.0.0-beta1 when running `publishReleaseBundle`. (gradle wrapper 4.6, Android gradle plugin 3.2.0).

**Comment by SUPERCILEX** [comment]
@mehdiraza Are you excluding or forcing our dependencies to a specific version? If you're getting the error, it's most likely due to your specific configuration.

**Comment by mehdiraza** [comment]
In my `build.gradle` I don't have any dependencies mentioned here: 
https://github.com/GoogleCloudPlatform/getting-started-java/issues/325#issuecomment-377171975

Do I need to add these in my `build.gradle`?

**Comment by SUPERCILEX** [comment]
You shouldn't have to. Can you show your build files?

**Comment by SUPERCILEX** [comment]
Those are your app dependencies. Please `./gradlew buildEnvironment`

**Comment by mehdiraza** [comment]
http://snippi.com/s/60g2xcv

**Comment by SUPERCILEX** [comment]
I'm not seeing the plugin at all in your classpath. Please follow the instructions in the README.

**Comment by mehdiraza** [comment]
Ah, I had the class path in the project's gradle instead of app's. Works now, thanks a lot!

**Comment by SUPERCILEX** [comment]
No problem! 😊

**Comment by shalzz** [comment]
Hi,
I'm getting the same error with the v2.0.0-rc2 published on the gradle plugins portal.
Since this plugin in no longer on the project level classpath.
Do I need to declare this plugin in the classpath of `buildscript` ?

**Comment by Pitel** [comment]
I'm also seeing this, ag\fter upgrading from 1.2.2 to 2.0.0.

## Stack trace

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bonnie:publishReleaseBundle'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
        at com.google.api.services.androidpublisher.AndroidPublisher$Builder.setBatchPath(AndroidPublisher.java:8381)
        at com.google.api.services.androidpublisher.AndroidPublisher$Builder.<init>(AndroidPublisher.java:8360)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase$publisher$2.invoke(PlayPublishTaskBase.kt:49)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase$publisher$2.invoke(PlayPublishTaskBase.kt:20)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.getPublisher(PlayPublishTaskBase.kt)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.read(PlayPublishTaskBase.kt:61)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.read$default(PlayPublishTaskBase.kt:58)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.write(PlayPublishTaskBase.kt:87)
        at com.github.triplet.gradle.play.tasks.PublishBundle.publishBundle(PublishBundle.kt:34)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
```

## buildEnvironment

```
> Task :bonnie:buildEnvironment

------------------------------------------------------------
Project :bonnie
------------------------------------------------------------

classpath
\--- com.github.triplet.play:com.github.triplet.play.gradle.plugin:2.0.0
     \--- com.github.triplet.gradle:play-publisher:2.0.0
          \--- com.google.apis:google-api-services-androidpublisher:v3-rev12-1.23.0
               \--- com.google.api-client:google-api-client:1.23.0
                    +--- com.google.oauth-client:google-oauth-client:1.23.0
                    |    +--- com.google.http-client:google-http-client:1.23.0
                    |    |    +--- com.google.code.findbugs:jsr305:1.3.9
                    |    |    \--- org.apache.httpcomponents:httpclient:4.0.1
                    |    |         +--- org.apache.httpcomponents:httpcore:4.0.1
                    |    |         +--- commons-logging:commons-logging:1.1.1
                    |    |         \--- commons-codec:commons-codec:1.3
                    |    \--- com.google.code.findbugs:jsr305:1.3.9
                    \--- com.google.http-client:google-http-client-jackson2:1.23.0
                         +--- com.google.http-client:google-http-client:1.23.0 (*)
                         \--- com.fasterxml.jackson.core:jackson-core:2.1.3

(*) - dependencies omitted (listed previously)
```

**Comment by SUPERCILEX** [comment]
Have you tried the [workaround](https://github.com/Triple-T/gradle-play-publisher/issues/344#issuecomment-398916398)?

**Comment by Pitel** [comment]
No, I didn't.
1. How can I updated dependencies in gradle plugin?
2. According to buildEnvironment, all google-something libraries already are 1.23.0.

**Comment by SUPERCILEX** [comment]
The problem is that none of us working on the project can repro. The best solution I can offer you is to start ripping classpath deps out until it works. However, if you do manage to make a MCVE, please share it.

**Comment by shalzz** [comment]
Ok, so it was firebase-perf causing this cryptic issue. I ended up removing it since it's causing way more problem than being helpful. Thanks.

**Comment by Sloy** [comment]
I can confirm, replacing `firebase-plugins` with `perf-plugin` fixes the issue. That's a tricky bug 😲 

I don't get why gradle uses the lower 1.22 version even when gradle-play-publisher declares the 1.23. But since we don't use the crash plugin, the workaround is good enough.

Thanks! We had a couple of projects affected by this issue.

**Comment by Pitel** [comment]
Still a problem with 2.1.0.

**Comment by scana** [comment]
Make sure your buildscript contains the following:
```groovy
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.google.firebase:firebase-plugins:1.1.5'
        classpath 'com.google.api-client:google-api-client:1.25.0' //<-----
        classpath 'com.google.http-client:google-http-client-jackson2:1.25.0' //<-----
        classpath 'com.google.http-client:google-http-client:1.25.0' //<-----
    }
}
```
and make sure that when you run `./gradlew buildEnvironment` you get those specific version.

**Comment by illia-kramarenko** [comment]
Also confirming that the problem was caused by the `com.google.firebase:firebase-plugins:1.15`
Fixed it this way:
```
buildscript {

    repositories {
        google()
        jcenter()
        // ...
    }

    dependencies {
        // ...
        classpath 'com.google.api-client:google-api-client:1.25.0'
        classpath('com.google.firebase:firebase-plugins:1.1.5') {
            exclude group: 'com.google.api-client', module: 'google-api-client'
        }
        // ...
    }
}
```

**Comment by hardysim** [comment]
The [firebase docs](https://firebase.google.com/docs/perf-mon/get-started-android#add-perfmon-plugin) have been updated as well to use `com.google.firebase:perf-plugin`:

> `firebase-plugins` is deprecated at v2.0.0.
Instead, you must add the Performance Monitoring plugin explicitly, as shown in the following steps.
